set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to gpio_1[0]
set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to gpio_1[1]
set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to gpio_1[2]
set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to gpio_1[3]
set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to gpio_1[4]
set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to gpio_1[5]
set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to gpio_1[6]
set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to gpio_1[7]
