NVC_SRC+=$(OsvvmLibraries)/AXI4/Axi4/src/Axi4ComponentPkg.vhd=osvvm_axi4
NVC_SRC+=$(OsvvmLibraries)/AXI4/Axi4/src/Axi4ComponentVtiPkg.vhd=osvvm_axi4
NVC_SRC+=$(OsvvmLibraries)/AXI4/Axi4/src/Axi4Context.vhd=osvvm_axi4
NVC_SRC+=$(OsvvmLibraries)/AXI4/Axi4/src/Axi4Manager.vhd=osvvm_axi4
NVC_SRC+=$(OsvvmLibraries)/AXI4/Axi4/src/Axi4ManagerVti.vhd=osvvm_axi4
NVC_SRC+=$(OsvvmLibraries)/AXI4/Axi4/src/Axi4Monitor_dummy.vhd=osvvm_axi4
NVC_SRC+=$(OsvvmLibraries)/AXI4/Axi4/src/Axi4Subordinate.vhd=osvvm_axi4
NVC_SRC+=$(OsvvmLibraries)/AXI4/Axi4/src/Axi4SubordinateVti.vhd=osvvm_axi4
NVC_SRC+=$(OsvvmLibraries)/AXI4/Axi4/src/Axi4Memory.vhd=osvvm_axi4
NVC_SRC+=$(OsvvmLibraries)/AXI4/Axi4/src/Axi4MemoryVti.vhd=osvvm_axi4
NVC_SRC+=$(OsvvmLibraries)/AXI4/Axi4/src/Axi4PassThru.vhd=osvvm_axi4
NVC_SRC+=$(OsvvmLibraries)/AXI4/Axi4/src/Axi4GenericSignalsPkg.vhd=osvvm_axi4
