#################################################################################
# makefile for tb_hram_ctrl_xilinx_7series
#################################################################################

FPGA_VENDOR=xilinx
FPGA_FAMILY=7series
include ../tb_hram_ctrl.mak
