= GHDL

GHDL is a very well established free and open source simulator for VHDL. For more information, visit the http://ghdl.free.fr/[GHDL home page].

The easiest way for Windows users to get GHDL running is to install it via MSYS2:

. Install MSYS2 if required by following <<msys2.adoc#,these steps>>.

. Install GHDL by entering the following command in an *MSYS2 MSYS* shell:

  pacman -S mingw-w64-x86_64-ghdl-llvm

. Check the GHDL version by entering the following command in an *MSYS2 MinGW x64* shell:

  ghdl --version
+
You should see something like this:
+
----
user@MACHINE MINGW64 ~
$ ghdl --version
GHDL 3.0.0-dev (2.0.0.r394.g4afeced94) [Dunoon edition]
 Compiled with GNAT Version: 12.1.0
 llvm code generator
Written by Tristan Gingold.

Copyright (C) 2003 - 2022 Tristan Gingold.
GHDL is free software, covered by the GNU General Public License.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

user@MACHINE MINGW64 ~
$
----

If you would like to build and install the latest version, instructions for MSYS2 are as follows:

. Open an *MSYS2 MinGW x64* shell.

. Ensure that the required build tools are installed:

  pacman -S base-devel mingw-w64-x86_64-{gcc,gnatcoll,llvm}

. Navigate to an appropriate working directory, and clone the GHDL repository:

  cd ~
  git clone https://github.com/libgit2/libgit2

. Navigate into the cloned repository, create a build subdirectory and navigate into that:

  cd ghdl
  mkdir build
  cd build

. Configure the build, specifying where to install it:

   ../configure --with-llvm-config --prefix=/mingw64/
 
 . Build and install GHDL:
 
   make
   make install
