= GHDL

GHDL is a very well established free and open source simulator for VHDL. For more information, visit the http://ghdl.free.fr/[GHDL home page].

== Installation on Windows

The easiest way for Windows users to get GHDL running is to install it via MSYS2:

. Install MSYS2 if required by following <<msys2.adoc#,these steps>>.

. Open an *MSYS2 MinGW x64* shell.

. Enter the following command to install GHDL:

  pacman -S mingw-w64-x86_64-ghdl-llvm

. To check the GHDL version, enter the following command:

  ghdl --version
+
You should see something like this:
+
----
user@MACHINE MINGW64 ~
$ ghdl --version
GHDL 3.0.0-dev (2.0.0.r394.g4afeced94) [Dunoon edition]
 Compiled with GNAT Version: 12.1.0
 llvm code generator
Written by Tristan Gingold.

Copyright (C) 2003 - 2022 Tristan Gingold.
GHDL is free software, covered by the GNU General Public License.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

user@MACHINE MINGW64 ~
$
----

=== AMD/Xilinx Vivado Libraries

To build the Vivado libraries:

. Open an *MSYS2 MinGW x64* shell.

. Navigate to the GHDL vendor library directory:

  cd /mingw64/lib/ghdl/vendors

. Edit the `Xilinx_Vivado_Settings` section of `config.sh` there to match your Vivado installation path, for example:

  declare -A Xilinx_Vivado_Settings=(
  	["InstallationDirectory"]="/c/Xilinx/Vivado/2022.1"
  	["SourceDirectory"]="data/vhdl/src"
  	["DestinationDirectory"]="xilinx-vivado"
  )

. Run the build script, specifying all libraries, for VHDL 1993 and 2008:

  ./compile-xilinx-vivado.sh -a --vhdl93
  ./compile-xilinx-vivado.sh -a --vhdl2008

**Note:** the process takes many minutes to complete. Some script warnings may be produced (the script was written to run on Linux systems).

When running GHDL analysis or elaboration, specify the path to these libraries with the following command line option:

  -P/mingw64/lib/ghdl/vendors/xilinx-vivado

=== Intel/Altera Quartus Libraries

To build the Quartus libraries:

. Open an *MSYS2 MinGW x64* shell.

. Navigate to the GHDL vendor library directory:

  cd /mingw64/lib/ghdl/vendors

. Edit the `Intel_Quartus_Settings` section of `config.sh` there to match your Quartus installation path, for example:

  declare -A Intel_Quartus_Settings=(
  	["InstallationDirectory"]="/c/intelFPGA_lite/21.1/quartus"
  	["SourceDirectory"]="eda/sim_lib"
  	["DestinationDirectory"]="intel"
  )

. Run the build script, specifying all libraries, for VHDL 1993 and 2008:

  ./compile-intel.sh -a --vhdl93
  ./compile-intel.sh -a --vhdl2008

**Note:** the process takes many minutes to complete. Some script warnings may be produced (the script was written to run on Linux systems).

When running GHDL analysis or elaboration, specify the path to these libraries with the following command line option:

  -P/mingw64/lib/ghdl/vendors/intel

=== Building GHDL from source

To build and install the latest version of GHDL from source:

. Open an *MSYS2 MinGW x64* shell.

. Ensure that the required build tools are installed:

  pacman -S base-devel mingw-w64-x86_64-{gcc,gnatcoll,llvm}

. Navigate to an appropriate working directory, and clone the GHDL repository there:

  cd ~
  git clone https://github.com/libgit2/libgit2

. Navigate into the cloned repository, create a build subdirectory and navigate into that:

  cd ghdl
  mkdir build
  cd build

. Configure the build, specifying where to install it:

   ../configure --with-llvm-config --prefix=/mingw64
 
 . Build and install GHDL:
 
   make
   make install
