= NVC

https://www.nickg.me.uk/nvc/[NVC] is a potent alternative to GHDL. It offers improved simulation run times and simple support for vendor libraries. It also fully supports the https://osvvm.org/[OSVVM] and https://www.uvvm.org/[UVVM] verification frameworks.

To get the latest version of NVC running on your system, you will need to build it from source. The following instructions are for Windows users:

. Install MSYS2 if required by following <<msys2.adoc#,these steps>>.

. Open an *MSYS2 MINGW64* terminal. Install NVC's build dependancies:

  pacman -S --neede3d base-devel mingw-w64-x86_64-{gcc,llvm,ncurses,libffi,check,pkg-config,autotools,ruby}

. Navigate to your chosen working directory. For example:

  cd /c/work

. Clone the NVC repository:

  git clone https://github.com/nickg/nvc

. Navigate to the cloned repo and generate the configure script:

  cd nvc
  ./autogen.sh

. Create a directory for the build and run the remaining steps in it:

  mkdir build && cd build
  ../configure
  make
  make install

. Check the NVC version - it will include a short commit hash:

  nvc --version

. **Optional**: build and install the Vivado libraries, setting the `XILINX_VIVADO` environment variable correctly for your system:

  export XILINX_VIVADO=/c/Xilinx/Vivado/2022.1/
  nvc --install vivado

. **Optional**: build and install the Quartus libraries:

  nvc --install quartus
