#################################################################################
# makefile for tb_hram_test_xilinx_7series
#################################################################################

FPGA_VENDOR=xilinx
FPGA_FAMILY=7series
include ../tb_hram_test.mak
