#################################################################################
# makefile for tb_hram_test_xilinx_7series
#################################################################################

FPGA_VENDOR=xilinx
FPGA_FAMILY=7series
VIVADO_SIM_WCFG=$(abspath .)/behav.wcfg
include ../tb_hram_test.mak
